### ISSUE TITLE
Failed to download deps

### ISSUE THREAD

**Issue by jtanza** [kit-clj/demo-guestbook#3]
Hi there! It seems that the jar versions specified for both `kit-undertow` (1.0.6) and `cider-nrepl` (0.35.3) aren't hosted on maven? Changing the versions to `1.0.5` and `0.35.1` seemed to do the trick for now. Not sure if I am missing something though.

```
λ ~/code/clojure/clojure/ clojure -Tnew create :template io.github.kit-clj :name kit/guestbook
λ ~/code/clojure/clojure/ cd guestbook/
λ ~/code/clojure/guestbook/ clj
Error building classpath. Could not find artifact io.github.kit-clj:kit-undertow:jar:1.0.6 in central (https://repo1.maven.org/maven2/)
λ ~/code/clojure/guestbook/ clj -M:dev:cider
Error building classpath. Could not find artifact cider:cider-nrepl:jar:0.35.3 in central (https://repo1.maven.org/maven2/)
```

**Comment by yogthos** [comment]
Thanks for the heads up. Looks like kit-undertow needed a release and I bumped up cider-nrepl to the latest on Clojars. Let me know if everything looks good.

**Comment by jtanza** [comment]
Working now - thank you friend!
